// =========================
// lib/simulation/replay.ts
// =========================
// Server-side integrity for scoring.
//
// The event log arrives from the browser, so it can't be trusted to be honest
// about anything the SERVER can work out for itself. Because the engine is
// deterministic, it can: keep only what the student actually did, and rebuild
// everything else from the case.
//
//   kept        history, exams, orders, interpretations, interventions,
//               differential / diagnosis / management, assist REQUESTS
//   re-derived  every STATE_TRANSITION and PATIENT_DETERIORATED (from the rules),
//               every intervention's consequence (from the case),
//               every assist's COST and whether it was allowed at all
//
// So a tampered client can't hide a deterioration, invent a stabilisation, or
// zero out its assist costs. What it can still do — claim it acted sooner than
// it did — is the same trust the rest of the app places in client-reported time.

import { EncounterEngine } from "./encounter-engine";
import type { ClinicalEvent } from "./encounter-events";
import { sanitizeEvents } from "./encounter-events";
import { hardLimitSeconds, type SimulationCaseConfig } from "./case-schema";
import { assistTypeForTest } from "../clinical-catalog";
import { getTestDef } from "./test-catalog";

export function replayStudentEvents(config: SimulationCaseConfig, untrusted: unknown): EncounterEngine {
    const engine = new EncounterEngine(config);
    const limit = hardLimitSeconds(config);
    const events = sanitizeEvents(untrusted);

    let lastStudentTime = 0;
    for (const event of events) {
        const timestamp = Math.min(event.timestamp, limit);
        lastStudentTime = Math.max(lastStudentTime, timestamp);

        switch (event.type) {
            // Regenerated by the engine from the case's rules.
            case "STATE_TRANSITION":
            case "PATIENT_DETERIORATED":
                break;

            // Consequence text and safety are the case's to decide. A case with no tray has nothing to give.
            case "INTERVENTION_GIVEN":
                if (config.available_interventions?.length === 0) break;
                engine.giveIntervention(event.action, timestamp);
                break;

            // Priced and permitted by the case's assist ladder, not by the client.
            case "ASSIST_USED":
                engine.requestAssist(event.assistType, timestamp, event.target);
                break;

            // The reveal is only real if it was paid for: route it through the same assist gate.
            case "RESULT_REVEALED": {
                const test = getTestDef(config, event.testId);
                if (!test || event.orderTimestamp === undefined) break;
                engine.revealResult({
                    testId: event.testId,
                    orderTimestamp: event.orderTimestamp,
                    revealType: event.revealType,
                    assistType: assistTypeForTest(test),
                    timestamp,
                });
                break;
            }

            default:
                engine.dispatch(withTimestamp(event, timestamp));
        }
    }

    // Let whatever became due after the student's last action happen.
    engine.advanceTo(lastStudentTime);
    return engine;
}

function withTimestamp(event: ClinicalEvent, timestamp: number): ClinicalEvent {
    return { ...event, timestamp } as ClinicalEvent;
}
