// The public study page for each case (/case-studies/[id]): how to approach the patient's presenting complaint,
// written the way a student would revise it. It is keyed by case id, and the ids already describe the patient, not
// the diagnosis (lib/cases/renamed-ids.ts).
//
// SPOILER RULE: nothing here may single out the case's diagnosis. The differential is broad and grouped, never
// ranked, and the history/exam/investigation lists are what you would do for ANY patient with this complaint.
// A case with no guide here still gets a page, but it is noindex (a title and two sentences is a thin page).
//
// Clinical content: standard undergraduate teaching, to be checked by a doctor before it goes live.

export interface CaseGuide {
    /** <title>, before the "| MediKarya" template. Keep it under ~55 characters. */
    seoTitle: string
    metaDescription: string
    h1: string
    /** The complaint in a phrase, as used in running text ("chest pain and sweating"). */
    complaint: string
    keywords: string[]
    /** Why this presentation matters, one short paragraph. */
    why: string
    history: string[]
    redFlags: string[]
    examination: string[]
    investigations: string[]
    /** Grouped, unranked. */
    differential: { group: string; items: string[] }[]
    pitfalls: string[]
}

export const CASE_GUIDES: Readonly<Record<string, CaseGuide>> = {
    "2-year-old-boy-with-vomiting-and-watery-diarrhea": {
        seoTitle: "Vomiting and Diarrhoea in a Toddler: Practice Case",
        metaDescription: "A free paediatric case for medical students: a 2-year-old with vomiting and watery diarrhoea. What to ask, how to assess dehydration, red flags and the differential to work through.",
        h1: "Vomiting and watery diarrhoea in a 2-year-old: a paediatric case to work up",
        complaint: "vomiting and watery diarrhoea in a young child",
        keywords: ["acute diarrhoea child case", "paediatric dehydration assessment", "vomiting diarrhoea toddler case MBBS", "paediatrics clinical case medical students"],
        why: "Acute diarrhoea is one of the commonest reasons a young child is brought to a doctor in India, and dehydration, not the infection itself, is what makes it dangerous. The skill is judging how dry the child is and spotting the few children whose vomiting is not coming from the gut at all.",
        history: [
            "Onset, and how many episodes of vomiting and stools in the last 24 hours",
            "What the stool looks like: watery, blood or mucus in it",
            "What the vomit looks like: food, bile (green) or blood",
            "Oral intake: is the child keeping any fluid down?",
            "Urine output: wet nappies or trips to the toilet in the last 12 hours",
            "Fever, abdominal pain, rash, unusual drowsiness or irritability",
            "Contacts with similar illness, food, water source, recent travel",
            "Immunisations (including rotavirus), recent antibiotics, past illnesses",
        ],
        redFlags: [
            "Lethargy, unusual drowsiness or difficulty waking the child",
            "Signs of shock: cold hands and feet, prolonged capillary refill, fast weak pulse",
            "Unable to drink, or vomiting everything",
            "Blood in the stool",
            "Green (bilious) vomiting, a distended or very tender abdomen",
            "Markedly reduced urine output",
            "High fever, a non-blanching rash or a stiff neck",
        ],
        examination: [
            "General condition: alert, irritable, or lethargic",
            "Weight, to compare with a recent weight and to calculate fluids",
            "Heart rate, capillary refill time, temperature of hands and feet",
            "Eyes (sunken?), tears, mouth and tongue",
            "Skin pinch on the abdomen: how fast it goes back",
            "Abdomen: distension, tenderness, masses, bowel sounds",
            "A quick look for other sources of illness: ears, throat, chest, rash",
        ],
        investigations: [
            "Often none, if the child is only mildly unwell and drinking",
            "Serum electrolytes, urea, creatinine and blood glucose if dehydration is more than mild or fluids go into a vein",
            "Stool microscopy and culture if there is blood, or the diarrhoea is prolonged",
            "Urine dipstick and culture if the cause is unclear",
        ],
        differential: [
            { group: "Infective (gut)", items: ["Viral gastroenteritis (rotavirus, norovirus)", "Bacterial gastroenteritis or dysentery", "Parasitic infection (giardia)", "Food poisoning"] },
            { group: "Infection elsewhere", items: ["Urinary tract infection", "Otitis media or pneumonia", "Meningitis or sepsis"] },
            { group: "Surgical", items: ["Intussusception", "Appendicitis", "Bowel obstruction"] },
            { group: "Metabolic", items: ["Diabetic ketoacidosis"] },
        ],
        pitfalls: [
            "Vomiting is not always gastroenteritis. Look for a surgical abdomen and for infection elsewhere before you settle.",
            "Underestimating dehydration. Use a structured scale (such as the WHO no / some / severe dehydration signs) rather than an impression.",
            "Ordering blood tests in a well, drinking child changes nothing and upsets everyone.",
        ],
    },

    "4-week-old-infant-with-yellow-eyes-and-face": {
        seoTitle: "Prolonged Neonatal Jaundice: Practice Case",
        metaDescription: "A paediatric case for medical students: a 4-week-old with jaundice since the first week. What to ask, the stool and urine questions you cannot skip, red flags, tests and the differential.",
        h1: "Jaundice in a 4-week-old: a prolonged neonatal jaundice case to work up",
        complaint: "jaundice lasting beyond the first two weeks of life",
        keywords: ["prolonged neonatal jaundice case", "jaundice in 4 week old baby", "neonatal jaundice approach medical students", "paediatrics case MBBS"],
        why: "Jaundice in the first week is common and usually harmless. Jaundice still present after two weeks in a term baby (three in a preterm one) is called prolonged jaundice, and most of it is benign too. The point of the work-up is to find the small number of babies with liver disease, where a delay of weeks changes the outcome.",
        history: [
            "When the jaundice started and whether it is getting better or worse",
            "Stool colour: yellow, pale, or chalky white",
            "Urine colour: pale, or dark yellow and staining the nappy",
            "Feeding: breast or formula, how often, how well",
            "Weight gain since birth",
            "Birth history: gestation, birth weight, any early jaundice needing phototherapy",
            "Mother's and baby's blood groups; family history of jaundice, anaemia, G6PD deficiency or liver disease",
            "Vomiting, poor feeding, sleepiness, constipation",
            "Results of the newborn screening tests, if done",
        ],
        redFlags: [
            "Pale or chalky stools, or dark urine",
            "A raised conjugated (direct) bilirubin",
            "Poor feeding, lethargy or poor weight gain",
            "An enlarged liver or spleen",
            "Bleeding or bruising",
            "Jaundice that is getting deeper rather than fading",
        ],
        examination: [
            "Extent of jaundice, and pallor",
            "Weight, length and head circumference plotted on a chart",
            "Hydration and general alertness",
            "Abdomen: liver and spleen size",
            "Signs of hypothyroidism: large tongue, umbilical hernia, dry skin, sluggishness",
            "Dysmorphic features, heart murmurs",
            "Look at a nappy: stool and urine colour",
        ],
        investigations: [
            "Total and conjugated (direct) bilirubin, the single most important first test",
            "Full blood count and blood film, reticulocyte count",
            "Blood group and direct antiglobulin (Coombs) test",
            "G6PD level",
            "Thyroid function (TSH and free T4)",
            "Urine culture",
            "Liver function tests if the conjugated fraction is raised",
        ],
        differential: [
            { group: "Unconjugated", items: ["Breast milk jaundice", "Haemolysis: ABO or Rh incompatibility, G6PD deficiency, hereditary spherocytosis", "Hypothyroidism", "Infection, especially urinary tract infection", "Gilbert or Crigler-Najjar syndrome"] },
            { group: "Conjugated (cholestatic)", items: ["Biliary atresia", "Choledochal cyst", "Neonatal hepatitis (infective or idiopathic)", "Metabolic disease such as galactosaemia", "Alpha-1 antitrypsin deficiency"] },
        ],
        pitfalls: [
            "Calling it breast milk jaundice without checking the conjugated bilirubin. That one test separates benign causes from ones that cannot wait.",
            "Not asking about, or looking at, the stool. Parents rarely mention pale stools unless asked.",
            "Reassuring a baby who is not gaining weight.",
        ],
    },

    "72-year-old-man-with-recurrent-fainting": {
        seoTitle: "Recurrent Syncope in an Older Man: Practice Case",
        metaDescription: "A cardiology case for medical students: a 72-year-old with recurrent fainting and a slow pulse. History, red flags, examination, the first tests and the differential for syncope.",
        h1: "Recurrent fainting and a slow pulse in a 72-year-old: a syncope case to work up",
        complaint: "recurrent fainting in an older adult",
        keywords: ["syncope case medical students", "recurrent syncope elderly approach", "bradycardia syncope case", "cardiology clinical case MBBS"],
        why: "Most fainting in young people is vasovagal. In an older person, unexplained syncope is treated as cardiac until proven otherwise, because some causes are fatal and most are treatable once found. The history, and an ECG, do most of the work.",
        history: [
            "What he was doing just before: standing, exerting, lying down, turning his head",
            "Warning symptoms beforehand (light-headedness, sweating, nausea) or none at all",
            "A witness account: colour, jerking, how long he was out, how fast he recovered",
            "Palpitations, chest pain or breathlessness around the episodes",
            "Injuries from falls, tongue biting, incontinence, confusion afterwards",
            "Medicines: beta-blockers, calcium channel blockers (verapamil, diltiazem), digoxin, antiarrhythmics, antihypertensives",
            "Previous heart disease, heart attack or heart surgery",
            "Family history of sudden death",
        ],
        redFlags: [
            "Fainting during exertion, or while lying down",
            "No warning before the episode",
            "A significant injury from the fall",
            "Chest pain or breathlessness with the episodes",
            "A very slow pulse while awake, or long pauses",
            "Low blood pressure or signs of heart failure",
            "A known structural heart problem, or a family history of sudden cardiac death",
        ],
        examination: [
            "Pulse: rate and rhythm, checked for a full minute",
            "Blood pressure lying and standing",
            "JVP",
            "Heart sounds and murmurs, especially an ejection systolic murmur",
            "Signs of heart failure: crackles, oedema",
            "Neurological examination, and a look for injuries",
        ],
        investigations: [
            "12-lead ECG, the first and most useful test",
            "Electrolytes, especially potassium, and renal function",
            "Blood glucose and full blood count",
            "Thyroid function",
            "Troponin if ischaemia is possible; drug levels such as digoxin if relevant",
            "Echocardiogram",
            "Continuous monitoring or ambulatory ECG if the cause is not caught on the first ECG",
        ],
        differential: [
            { group: "Reflex and postural", items: ["Vasovagal syncope", "Orthostatic hypotension (including from medicines)", "Carotid sinus hypersensitivity", "Situational syncope (cough, micturition)"] },
            { group: "Cardiac: rhythm", items: ["Sinus node disease", "Atrioventricular (heart) block", "Drug-induced bradycardia", "Ventricular tachycardia"] },
            { group: "Cardiac: structural", items: ["Aortic stenosis", "Hypertrophic cardiomyopathy", "Ischaemia or myocardial infarction"] },
            { group: "Not syncope", items: ["Seizure", "Hypoglycaemia", "Transient ischaemic attack (rarely causes loss of consciousness)"] },
        ],
        pitfalls: [
            "Accepting 'he just fainted' in an older man without an ECG.",
            "Missing a medicine (or a high potassium) that is slowing the heart.",
            "Calling the jerking seen in many faints a seizure. Brief jerks are common in syncope; a long post-ictal confusion is not.",
        ],
    },

    "24-year-old-man-with-fever-after-travel": {
        seoTitle: "Fever After Travel to Africa: Practice Case",
        metaDescription: "An infectious disease case for medical students: fever, rigors and malaise after a trip to Nigeria. The travel history, red flags, first tests and differential for fever in a returning traveller.",
        h1: "Fever after returning from Nigeria: a returning-traveller case to work up",
        complaint: "fever in a returning traveller",
        keywords: ["fever in returning traveller case", "fever after travel approach medical students", "tropical fever case MBBS", "infectious disease clinical case"],
        why: "A fever after travel to the tropics is a medical emergency until a few dangerous causes are ruled out, because some of them can go from mild to life-threatening within a day. The travel history, taken carefully, narrows the list fast.",
        history: [
            "Exactly where he went (cities, rural areas), and the dates of arrival and return",
            "Antimalarial prophylaxis: which drug, and whether he took it as prescribed, including after return",
            "Mosquito bite precautions: nets, repellent",
            "Vaccinations before travel (yellow fever, typhoid, hepatitis A)",
            "Food and water: street food, untreated water",
            "Fresh water swimming, animal contact, insect or tick bites",
            "Sexual contacts, and contact with anyone who was ill",
            "The fever itself: when it started, rigors, pattern; headache, cough, diarrhoea, rash, jaundice, bleeding",
        ],
        redFlags: [
            "Confusion, drowsiness or seizures",
            "Jaundice",
            "Breathlessness or low oxygen saturation",
            "Bleeding: gums, nose, skin, urine",
            "Low blood pressure or low urine output",
            "Low blood glucose",
            "Severe anaemia",
        ],
        examination: [
            "Temperature, pulse, blood pressure, respiratory rate, oxygen saturation",
            "Conscious level",
            "Jaundice, pallor, rash, bleeding",
            "Liver and spleen size",
            "Chest, and a look for neck stiffness",
            "Lymph nodes, throat, skin (eschar, bites)",
        ],
        investigations: [
            "Malaria test today: thick and thin blood films and/or a rapid diagnostic test",
            "If negative, repeat the films, typically up to three sets over 48 to 72 hours",
            "Full blood count, renal function, liver function, blood glucose",
            "Blood cultures, urine routine and culture",
            "Dengue NS1 or serology, depending on the timing",
            "Chest X-ray if there are chest symptoms; HIV test",
        ],
        differential: [
            { group: "Must not miss", items: ["Malaria", "Typhoid (enteric fever)", "Bacterial sepsis", "Viral haemorrhagic fever (Lassa fever in West Africa, with a suggestive exposure)"] },
            { group: "Common tropical", items: ["Dengue", "Viral hepatitis", "Leptospirosis", "Rickettsial infection"] },
            { group: "Ordinary infections", items: ["Influenza or other viral illness", "Pneumonia", "Urinary tract infection"] },
            { group: "Other", items: ["Acute HIV infection", "Schistosomiasis (Katayama fever)"] },
        ],
        pitfalls: [
            "A single negative malaria film does not rule malaria out.",
            "Forgetting that taking prophylaxis lowers the risk but does not remove it.",
            "Sending a feverish traveller home to 'see how it goes' before malaria is excluded.",
        ],
    },

    "54-year-old-woman-with-a-neck-swelling": {
        seoTitle: "Neck Swelling With Voice Change: Practice Case",
        metaDescription: "A case for medical students: a 54-year-old woman with a neck swelling, difficulty swallowing and a change in voice. History, thyroid examination, red flags, tests and the differential.",
        h1: "A neck swelling with difficulty swallowing in a 54-year-old: a case to work up",
        complaint: "a neck swelling with pressure symptoms",
        keywords: ["neck swelling case medical students", "thyroid swelling examination approach", "goitre case MBBS", "neck lump differential diagnosis"],
        why: "Most neck swellings in the front of the neck are thyroid, and most thyroid swellings are benign. The work-up has two jobs: decide whether the gland is working normally, and decide whether the swelling could be cancer or is pressing on the windpipe, gullet or the nerve to the voice box.",
        history: [
            "How long the swelling has been there, and whether it is growing, and how fast",
            "Pain or tenderness",
            "Pressure symptoms: difficulty swallowing, breathlessness, noisy breathing, change in voice",
            "Symptoms of an overactive thyroid (weight loss, heat intolerance, palpitations, tremor) or an underactive one (weight gain, cold intolerance, constipation, tiredness)",
            "Weight loss, fevers or night sweats",
            "Radiation to the neck in the past; family history of thyroid disease or thyroid cancer",
            "Where she lives and her diet (iodine), medicines",
        ],
        redFlags: [
            "Rapid growth",
            "A hard, irregular or fixed swelling",
            "Hoarseness or a change in voice",
            "Stridor or breathlessness",
            "Enlarged lymph nodes in the neck",
            "Weight loss or night sweats",
            "Past radiation to the neck",
        ],
        examination: [
            "Inspect from the front: does it move up on swallowing? On sticking the tongue out?",
            "Palpate from behind: size, surface (smooth, nodular), consistency, tenderness",
            "Whether you can get below it (retrosternal extension), and tracheal position",
            "Cervical lymph nodes",
            "Thyroid status: pulse, tremor, skin, reflexes, eye signs",
            "Pemberton's sign if retrosternal extension is suspected",
        ],
        investigations: [
            "TSH, with free T4 if TSH is abnormal",
            "Ultrasound of the neck",
            "Fine needle aspiration cytology (FNAC) of a suspicious nodule",
            "Laryngoscopy to look at the vocal cords when the voice has changed",
            "CT of the neck and chest if retrosternal extension or tracheal compression is suspected",
            "Thyroid antibodies",
        ],
        differential: [
            { group: "Thyroid", items: ["Multinodular goitre", "Solitary nodule or adenoma", "Thyroid cancer (papillary, follicular, medullary, anaplastic)", "Thyroiditis, including Hashimoto's", "Graves' disease", "Thyroid cyst"] },
            { group: "Not thyroid", items: ["Lymph nodes: tuberculosis, lymphoma, metastatic cancer", "Thyroglossal or branchial cyst", "Salivary gland swelling"] },
        ],
        pitfalls: [
            "A normal TSH says the gland is working normally. It says nothing about whether a nodule is benign.",
            "Not examining the vocal cords when the voice has changed.",
            "Forgetting tuberculosis as a cause of neck lumps in India.",
        ],
    },

    "63-year-old-woman-with-tiredness-and-numb-feet": {
        seoTitle: "Tiredness, Breathlessness and Numb Feet: Practice Case",
        metaDescription: "A haematology case for medical students: a 63-year-old woman with tiredness, breathlessness and numbness in her feet. History, neurological examination, first blood tests and the differential.",
        h1: "Tiredness, breathlessness and numb feet in a 63-year-old: a case to work up",
        complaint: "tiredness and breathlessness with numbness in the feet",
        keywords: ["anaemia with neuropathy case", "tiredness and numbness approach", "haematology clinical case medical students", "anaemia case MBBS"],
        why: "Tiredness on its own is one of the vaguest complaints in medicine. Tiredness with breathlessness suggests anaemia or heart and lung disease; add numb feet and unsteadiness, and the two complaints may share one cause. Linking them is the skill this case asks for.",
        history: [
            "How long, and how the tiredness and breathlessness have progressed",
            "The numbness: where it started, whether it is spreading, whether she is unsteady, worse in the dark",
            "Memory, mood or concentration changes",
            "Diet: vegetarian or vegan, how much she eats",
            "Bowel symptoms, weight loss, previous stomach or bowel surgery",
            "Bleeding: heavy periods (if still menstruating), black stools, blood in stools",
            "Alcohol",
            "Medicines: metformin, proton pump inhibitors",
            "Other autoimmune conditions in her or her family: thyroid disease, vitiligo, diabetes",
        ],
        redFlags: [
            "Rapidly worsening weakness, falls or unsteadiness",
            "Confusion or memory loss",
            "Breathlessness at rest or chest pain",
            "Weight loss or blood in the stool",
            "Low counts in more than one cell line (anaemia with low platelets or white cells)",
        ],
        examination: [
            "Pallor, a slightly yellow tinge, a smooth sore tongue, mouth ulcers",
            "Vitiligo, thyroid swelling",
            "Pulse, a flow murmur, signs of heart failure",
            "Neurological examination of the legs: tone, power, reflexes, plantar responses",
            "Vibration and joint position sense, and Romberg's test",
            "Gait",
        ],
        investigations: [
            "Full blood count with MCV, and a blood film",
            "Reticulocyte count",
            "Vitamin B12, folate and ferritin",
            "Thyroid function",
            "Blood glucose or HbA1c",
            "Renal and liver function, LDH and bilirubin",
        ],
        differential: [
            { group: "Nutritional and absorptive", items: ["Vitamin B12 deficiency (pernicious anaemia, diet, malabsorption)", "Folate deficiency", "Iron deficiency", "Coeliac disease"] },
            { group: "Endocrine and metabolic", items: ["Hypothyroidism", "Diabetes with peripheral neuropathy", "Chronic kidney disease"] },
            { group: "Toxic", items: ["Alcohol-related neuropathy and macrocytosis", "Medicines"] },
            { group: "Marrow and malignancy", items: ["Myelodysplasia", "Myeloma", "Other malignancy"] },
        ],
        pitfalls: [
            "Treating 'tiredness' as age or stress without a blood count.",
            "Testing the sensation in the feet with a pin only. Vibration and position sense pick up a different set of nerve problems.",
            "Starting folic acid on its own before vitamin B12 deficiency is excluded.",
        ],
    },

    "24-year-old-pregnant-woman-with-fatigue-and-breathlessness": {
        seoTitle: "Fatigue and Breathlessness in Pregnancy: Practice Case",
        metaDescription: "An obstetrics case for medical students: a 24-year-old at 28 weeks with fatigue, breathlessness and light-headedness. What to ask, red flags, examination, tests and the differential.",
        h1: "Fatigue and breathlessness at 28 weeks of pregnancy: an obstetrics case to work up",
        complaint: "fatigue and breathlessness in pregnancy",
        keywords: ["anaemia in pregnancy case", "breathlessness in pregnancy approach", "obstetrics clinical case medical students", "pregnancy case MBBS"],
        why: "Some tiredness and breathlessness is normal in pregnancy, which is exactly why the abnormal causes get missed. Anaemia is very common in pregnant women in India and affects both mother and baby; a few causes of breathlessness, such as a clot in the lung, are rarer but dangerous.",
        history: [
            "How the tiredness and breathlessness started, and whether they are worse on exertion or at rest",
            "Light-headedness, fainting, palpitations, chest pain",
            "Diet, and whether she takes her iron and folic acid tablets (and any side effects stopping her)",
            "Previous pregnancies, and the gap since the last one",
            "Heavy periods before pregnancy, bleeding in this pregnancy",
            "Craving for non-food items (pica), worm infestation, piles",
            "Personal or family history of anaemia or thalassaemia",
            "Leg swelling or pain, headache, visual disturbance",
            "Fetal movements",
        ],
        redFlags: [
            "Breathlessness at rest, chest pain or fainting",
            "A fast heart rate at rest or low oxygen saturation",
            "A swollen, painful calf",
            "Raised blood pressure, headache or visual disturbance",
            "Vaginal bleeding",
            "Reduced fetal movements",
            "Haemoglobin below 7 g/dL",
        ],
        examination: [
            "Pallor, nails (spoon-shaped?), tongue, angles of the mouth",
            "Pulse, blood pressure, respiratory rate, oxygen saturation",
            "Heart sounds and murmurs, chest",
            "Legs: oedema, calf swelling or tenderness",
            "Abdomen: fundal height for dates, fetal heart",
        ],
        investigations: [
            "Haemoglobin and full blood count with red cell indices (MCV, MCH)",
            "Serum ferritin",
            "Peripheral blood smear",
            "Haemoglobin electrophoresis or HPLC if the cells are small and iron stores are normal",
            "Stool for ova and parasites, urine routine",
            "ECG and further tests if a cardiac or lung cause is suspected",
        ],
        differential: [
            { group: "Anaemia", items: ["Iron deficiency", "Physiological (dilutional) fall in haemoglobin", "Thalassaemia trait", "Folate or vitamin B12 deficiency", "Blood loss, including hookworm"] },
            { group: "Heart and lung", items: ["Normal breathlessness of pregnancy", "Pulmonary embolism", "Heart disease in pregnancy (rheumatic valve disease, cardiomyopathy)", "Asthma"] },
            { group: "Other", items: ["Thyroid dysfunction", "Infection"] },
        ],
        pitfalls: [
            "Putting all breathlessness down to pregnancy.",
            "Relying on haemoglobin alone. Ferritin tells you about iron stores; a smear and indices point to the type of anaemia.",
            "Missing thalassaemia trait, which looks like iron deficiency on a blood count but does not respond to iron.",
        ],
    },

    "49-year-old-woman-with-flank-pain-and-blood-in-urine": {
        seoTitle: "Flank Pain and Blood in Urine: Practice Case",
        metaDescription: "A nephrology case for medical students: a 49-year-old woman with recurrent flank pain, visible blood in the urine and high blood pressure. History, examination, tests and the differential.",
        h1: "Flank pain and blood in the urine in a 49-year-old: a nephrology case to work up",
        complaint: "flank pain with blood in the urine",
        keywords: ["haematuria case medical students", "flank pain and haematuria approach", "nephrology clinical case MBBS", "blood in urine differential diagnosis"],
        why: "Visible blood in the urine in an adult always needs explaining, because one of the causes is cancer of the kidney or bladder. Flank pain, high blood pressure and what you can feel in the abdomen narrow the field quickly.",
        history: [
            "The pain: where, how it started, colicky or constant, radiation to the groin, how often it recurs",
            "The blood: throughout the stream or only at the start or end, clots",
            "Fever, burning on passing urine, frequency",
            "Previous kidney stones or urinary infections",
            "Headaches, high blood pressure, how long it has been known",
            "Family history of kidney disease, dialysis, brain haemorrhage or sudden death",
            "Painkillers (NSAIDs), smoking, weight loss",
        ],
        redFlags: [
            "Fever with flank pain (an infected or obstructed kidney)",
            "Falling urine output or rising creatinine",
            "Clots or heavy bleeding",
            "Weight loss",
            "A sudden, severe headache",
            "Very high blood pressure",
        ],
        examination: [
            "Blood pressure",
            "Abdomen: palpate each kidney with two hands (ballotable?), liver size",
            "Flank (renal angle) tenderness",
            "Heart murmurs",
            "Oedema, signs of anaemia or uraemia",
        ],
        investigations: [
            "Urinalysis and urine microscopy (red cells, casts, protein)",
            "Urine culture",
            "Serum creatinine, urea and electrolytes; full blood count",
            "Ultrasound of the kidneys and urinary tract",
            "CT (urography or non-contrast for stones) depending on the ultrasound",
        ],
        differential: [
            { group: "Kidney structure", items: ["Polycystic kidney disease", "Simple renal cysts", "Hydronephrosis"] },
            { group: "Stones and infection", items: ["Kidney or ureteric stones", "Pyelonephritis or an infected cyst"] },
            { group: "Tumour", items: ["Renal cell carcinoma", "Urothelial (bladder or ureteric) cancer"] },
            { group: "Glomerular", items: ["IgA nephropathy or other glomerulonephritis"] },
        ],
        pitfalls: [
            "Calling every haematuria a stone or infection without imaging.",
            "Not asking about the family. Several kidney diseases are inherited, and the family history is often the clue.",
            "Ignoring the blood pressure, which can be a cause, a consequence or both.",
        ],
    },

    "21-year-old-woman-with-visual-disturbances-and-headache": {
        seoTitle: "Headache With Visual Flashes: Practice Case",
        metaDescription: "A neurology case for medical students: a 21-year-old with recurrent severe headaches preceded by flashing lights. History, headache red flags, examination, when to image and the differential.",
        h1: "Recurrent headache with flashing lights in a 21-year-old: a neurology case to work up",
        complaint: "recurrent headache with visual symptoms",
        keywords: ["headache case medical students", "headache red flags approach", "headache with visual disturbance", "neurology clinical case MBBS"],
        why: "Headache is one of the commonest complaints in any clinic, and almost all of it is primary headache. The job is to make a confident diagnosis from the history, and to know the handful of features that mean this headache is different and needs more.",
        history: [
            "The visual symptoms: what she sees, how they spread, how long they last, whether they are in one eye or both",
            "Other symptoms before the headache: tingling, numbness, weakness, difficulty speaking",
            "The headache: site, character, how quickly it peaks, how long it lasts",
            "Nausea, vomiting, sensitivity to light and sound",
            "How often, and what triggers it: sleep, stress, food, periods",
            "How many days a month she takes painkillers",
            "Contraceptive pill use",
            "Family history of similar headaches",
        ],
        redFlags: [
            "A sudden, thunderclap headache, or the worst headache of her life",
            "Fever, neck stiffness or a rash",
            "Weakness, numbness or visual loss that does not go away",
            "Aura lasting more than an hour, or aura without a headache for the first time",
            "Headache worse lying down or on coughing, or with papilloedema",
            "A new headache in pregnancy or in someone with cancer or low immunity",
        ],
        examination: [
            "Full neurological examination, including visual fields and eye movements",
            "Fundoscopy for papilloedema",
            "Blood pressure",
            "Neck stiffness, temporal tenderness",
        ],
        investigations: [
            "Often none, if the history is typical and the examination is normal",
            "Imaging (CT or MRI) only if there are red flags",
            "A headache diary to record frequency, triggers and painkiller use",
        ],
        differential: [
            { group: "Primary headache", items: ["Migraine with or without aura", "Tension-type headache", "Cluster headache", "Medication overuse headache"] },
            { group: "Secondary, must not miss", items: ["Subarachnoid haemorrhage", "Cerebral venous sinus thrombosis", "Idiopathic intracranial hypertension", "Meningitis"] },
            { group: "Mimics of the visual symptoms", items: ["Transient ischaemic attack", "Occipital lobe seizure", "Retinal detachment (flashes in one eye)"] },
        ],
        pitfalls: [
            "Imaging everyone. A typical history with a normal examination rarely needs a scan.",
            "Not asking about the contraceptive pill. It matters for which treatments are safe.",
            "Missing medication overuse, which keeps headaches going.",
        ],
    },

    "61-year-old-man-with-severe-chest-pain-and-sweating": {
        seoTitle: "Chest Pain and Sweating: Live Emergency Case",
        metaDescription: "A live emergency case for medical students: a 61-year-old with severe chest pain and sweating whose vitals change with what you do. History, red flags, the first ten minutes and the differential.",
        h1: "Severe chest pain and sweating in a 61-year-old: a live emergency case",
        complaint: "acute chest pain with sweating",
        keywords: ["chest pain case medical students", "acute chest pain approach", "chest pain emergency case MBBS", "cardiology emergency simulation"],
        why: "Acute chest pain is the presentation where minutes matter most. Several of its causes kill quickly and need opposite treatments, so the first ten minutes are about recognising which one you are dealing with, while keeping the patient safe.",
        history: [
            "Onset: sudden or gradual, and what he was doing",
            "Character: crushing, tight, tearing, sharp; worse on breathing or moving",
            "Radiation: arm, jaw, back",
            "How long it has lasted",
            "Sweating, nausea, breathlessness, palpitations, fainting",
            "Risk factors: smoking, diabetes, high blood pressure, cholesterol, family history",
            "Previous heart disease, angina, stents",
            "Recent immobility or travel, leg swelling; drug use",
        ],
        redFlags: [
            "Pain lasting more than 20 minutes, or ongoing",
            "Low blood pressure, cold clammy skin, confusion",
            "Breathlessness or crackles in the chest",
            "An irregular or very fast or slow pulse",
            "Tearing pain going through to the back, or unequal blood pressure in the two arms",
            "Low oxygen saturation",
        ],
        examination: [
            "Airway, breathing, circulation: get the vital signs straight away",
            "Blood pressure in both arms; pulses",
            "Heart sounds, new murmurs, JVP",
            "Chest: crackles, air entry on each side",
            "Legs: swelling or tenderness",
        ],
        investigations: [
            "12-lead ECG within 10 minutes of arrival, and repeated if the pain changes",
            "Cardiac troponin, repeated as per protocol",
            "Chest X-ray",
            "Full blood count, electrolytes, renal function, glucose, coagulation",
            "Further imaging (echo, CT) guided by what the ECG and examination show",
        ],
        differential: [
            { group: "Cardiac", items: ["Acute coronary syndrome (STEMI, NSTEMI, unstable angina)", "Pericarditis", "Myocarditis"] },
            { group: "Vascular and lung", items: ["Aortic dissection", "Pulmonary embolism", "Tension pneumothorax", "Pneumonia"] },
            { group: "Gut and chest wall", items: ["Oesophageal rupture", "Reflux or oesophageal spasm", "Musculoskeletal pain"] },
        ],
        pitfalls: [
            "Waiting for a troponin result when the ECG already shows what to do.",
            "Giving blood thinners before considering aortic dissection.",
            "Being reassured by a normal first ECG or first troponin. Both can be normal early.",
        ],
    },
}
